import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "#ffffff",
  },
  notify: {
    width: 30,
    height: 30,
    borderRadius: 15,
    fontSize: 14,
    backgroundColor: "#E22982",
    overflow: "hidden",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#E26C29",
    alignItems: "center",
    justifyContent: "center",
    color: "#ffffff",
    position: "absolute",
    left: -15,
    top: -10,
    lineHeight: 29,
  },
  cash: {
    backgroundColor: "#E26C29",
  },
  banner: {
    flex: 2,
    borderRadius: 12,
  },
  introLabel: {
    color: "#BF4B0A",
    fontWeight: 700,
    backgroundColor: "#F8B757",
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    height: 27,
    width: 94,
  },
  button: {
    border: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
  },
  arrowButton: {
    border: 0,
    backgroundColor: "transparent",
    overflow: "hidden",
    alignItems: "center",
  },
  playVideo: {
    width: 46,
    height: 41,
    borderRadius: 12,
    backgroundColor: "#157BF2",
    justifyContent: "center",
  },
  arrowIcon: {
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderLeftColor: "transparent",
    borderRightWidth: 6,
    borderRightColor: "transparent",
    borderTopWidth: 10,
    borderTopColor: "#ffffff",
    transform: [{ rotate: "270deg" }],
  },
  popularGameTitle: {
    fontSize: 32,
    fontWeight: 700,
    color: "#157BF2",
    marginBottom: 4,
    marginLeft: 10,
  },
  bannerGame: {
    // height: 220,
    // width: 167,
    // flex: 1,
    // gap: 10,
    // marginLeft: 5,
    height: 220,
        flex: 1,
  },
  coin: {
    flexDirection: "row",
    marginLeft: 16,
    width: 44,
    height: 36,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#A4CDFE",
    borderRadius: 10,
    backgroundColor: "#CFE5FF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
    elevation:4,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  iconCoin: {
    height: 27,
    width: 32,
  },
  iconWrap: {
    width: 20,
    height: 20,
    justifyContent: "center",
  },
  headerRight: {
    // flex: 1,
    // justifyContent: "flex-end",
    alignItems: "center",
    flexDirection: "row",
    // marginRight: -25,
  },
  profilePic: {
    marginLeft: 10,
    width: 60,
    height: 60,
    borderRadius: 30,
    shadowColor: "rgba(0, 0, 0, 0.12)",
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 12,
  },
  headerLeft: {
    flex: 1,
    // marginLeft: -15,
  },
});
